DROP FUNCTION IF EXISTS add_them(integer, integer);
DROP SCHEMA IF EXISTS configuration CASCADE;
DROP SCHEMA IF EXISTS api CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS backend CASCADE;
DROP ROLE IF EXISTS web_anon;
DROP ROLE IF EXISTS todo_user;
DROP TYPE IF EXISTS jwt_token CASCADE;
DROP EXTENSION IF EXISTS pgjwt;
